In [2]:
import pandas as pd

In [ ]:
df1 = pd.read_excel('/Users/theo/Desktop/P.IVA/Aziende/Ermes/Modelli/scheda_gruppi_dpi/modello_scheda_gruppi_dpi_v2.xlsx', sheet_name='Scheda_mansioni', header=1)
df2 = pd.read_excel('/Users/theo/Desktop/P.IVA/Aziende/Ermes/Lavori/SITITALIA spa.p/rev/rev/Rumore/misure/data/averaged_data.xlsx')

In [ ]:
df1
df1['ID_GrOm']

In [ ]:
df1[df1['ID_GrOr']==1]['Ti'].values

In [ ]:
df2

In [ ]:
# df1 = df1.merge(
#     df2[['ID', 'U', 'LeqA', 'LeqC', 'Ppeak']],
#     left_on='ID_misura',
#     right_on='ID',
#     how='left',
#     indicator=True
# )

df2 = df2.merge(
    df1[['ID_misura']],
    left_on='ID',
    right_on='ID_misura',
    how = 'left',
    indicator=True
)
missing = df1.loc[df1['_merge'] == 'left_only', 'ID_misura'].unique().tolist()
# print(missing)

# df1 = df1.drop(columns=['ID', '_merge'])
# df1

In [ ]:
list_grom = df1[df1.columns[0]].unique()
print('list grom = ',list_grom)

for i in list_grom:
    df = df1[df1[df1.columns[0]] == i]
    print(df)
    match_idx = df2.index[df2[df2.columns[1]].isin(df[df.columns[5]])].tolist()
    print(match_idx)

    df.loc[:, 'LAeq'] = df2.iloc[match_idx, 3].values
    print(df)

    
    
    
    # df.drop(df.columns[[0, 2, 3]], axis=1).to_excel('df_filtered.xlsx', index=False)

In [59]:
sn = pd.ExcelFile('/Users/theo/Desktop/P.IVA/Aziende/Ermes/Lavori/SITITALIA spa.p/rev/rev8/Rumore/output/VR8h_totale.xlsx').sheet_names
df = pd.read_excel('/Users/theo/Desktop/P.IVA/Aziende/Ermes/Lavori/SITITALIA spa.p/rev/rev8/Rumore/output/VR8h_totale.xlsx', sheet_name=sn[2])
df

,ID_GrOm,Descrizione_GrOm,ID_reparto,Descrizione_reparto,Descrizione_compito,ID_misura,Ti,WBV,HAV,U,LeqA,LeqC,Ppeak
0,3,Addetto colori,NaN,NaN,Area colori - Addetto colorista bordo macchina,D2,60,NaN,NaN,1.5,82.2,86.9,114.1
1,3,Addetto colori,NaN,NaN,Area colori - Addetto colorista bordo macchina,D3,60,NaN,NaN,1.0,82.1,86.8,112.2
2,3,Addetto colori,NaN,NaN,Colorista - Addetto colorista bordo macchina,W2,60,NaN,NaN,1.6,85.1,88.4,117.2
3,3,Addetto colori,NaN,NaN,Postazione pc - Addetto colorista formulazione,D6,60,NaN,NaN,2.4,72.7,78.3,109.8
4,3,Addetto colori,NaN,NaN,Preparazione manuale - Addetto colorista formu...,E6,60,NaN,NaN,1.9,73.3,78.9,105.8
5,3,Addetto colori,NaN,NaN,Magazzino - Addetto colorista formulazione,E7,60,NaN,NaN,2.2,63.0,67.6,98.1
6,3,Addetto colori,NaN,NaN,Movimentazione con traspallet uomo a bordo - A...,W5,110,VIB1,NaN,2.9,79.4,81.7,117.6
7,3,Addetto colori,NaN,NaN,Sala ristoro Piano 1°,F9,10,NaN,NaN,0.9,59.2,67.2,101.3

In [82]:
df_dpi = pd.read_excel('/Users/theo/Desktop/scheda_gruppi_dpi.xlsx', header=1)
df_dpi['PNR'] = 0
df_dpi['LeqA_rid'] = 0

df_dpi.loc[0, 'LeqA_rid'] = 1
df_dpi

,codice_DPI,Descrizione,Marca,Modello,SNR,H,L,M,Beta,PNR,LeqA_rid
0,DPI1,Inserti su calco dell'orecchio mordidi,CRAI,HEAR PROTECTOR C4,24.9,27.4,21.5,18.6,0.5,0,1
1,DPI2,Inserti su calco dell'orecchio rigidi,ACOUSTIC SYSTEM,AUDIODEFENDER,18.9,22.9,15.1,11.7,0.5,0,0
2,DPI3,inserto preformato in TPR rilevabili,PORTWEST,EAR PLUG EP07,30.0,29.0,28.0,25.0,0.3,0,0

In [ ]:
df_out = pd.read_excel('/Users/theo/Desktop/P.IVA/Aziende/Ermes/Lavori/SITITALIA spa.p/rev/rev8/Rumore/output/VR8h_riepilogo.xlsx', header=0)
result = df_out[df_out['ID_GrOm'].astype(str) == '4']
result

,ID_GrOm,Mansione,Lex8h,U,Lex_max,L_picco_C,classe_rischio
0,1,Adetto stampa,81.6,1.3,82.9,128.0,MEDIA
1,2,Addetti supporto alla stampa,83.4,2.6,86.0,120.3,ALTA
2,3,Addetto colori,80.3,1.3,81.5,117.6,MEDIA
3,4,Addetti accoppiamento,83.7,0.8,84.4,128.8,MEDIA
4,4a,Addetti accoppiamento 2,84.0,2.2,86.2,117.6,ALTA
5,5,Addetti al taglio,81.2,2.3,83.5,122.9,MEDIA
6,6,Addetto supporto al taglio,75.8,1.3,77.2,114.1,BASSA
7,7,Addetti laboratorio,53.5,1.6,55.1,101.3,BASSA
8,8,Magazzinierie -addetto servizi generali,78.7,1.7,80.4,139.5,MEDIA
9,9,Manutentore,80.4,0.6,81.0,120.3,MEDIA
10,10,Addetto pulizie,78.2,6.5,84.8,115.6,MEDIA
11,11,Impiegato,56.4,2.2,58.5,101.3,BASSA
12,12,Impiegato tecnico,80.2,1.5,81.8,128.8,MEDIA