In [137]:
import pandas as pd

df1 = pd.read_excel('/Users/theo/Desktop/P.IVA/Aziende/Ermes/Modelli/scheda_gruppi_dpi/modello_scheda_gruppi_dpi_v2.xlsx', sheet_name='Scheda_mansioni', header=1)
df2 = pd.read_excel('/Users/theo/Desktop/P.IVA/Aziende/Ermes/Lavori/SITITALIA spa.p/rev/rev/Rumore/misure/data/averaged_data.xlsx')

In [ ]:
df1
df1['ID_GrOm']

0    1
1    1
2    3
Name: ID_GrOm, dtype: int64

In [132]:
df1[df1['ID_GrOr']==1]['Ti'].values

array([120,  60])

In [76]:
df2

                       jobName   ID    U  LeqA  LeqC  Ppeak  Ti GrOm DPI
0   20260325_101842_103414.csv   F1  2.8  80.6  85.0  108.0  []   []  []
1   20260325_103430_105156.csv   F2  1.4  81.5  86.0  115.6  []   []  []
2   20260325_105210_111209.csv   F3  0.7  83.0  87.4  115.1  []   []  []
3   20260325_111227_112948.csv   F4  1.8  82.9  87.0  107.5  []   []  []
4   20260325_113242_115130.csv   F5  0.6  77.9  81.5  102.3  []   []  []
..                         ...  ...  ...   ...   ...    ...  ..  ...  ..
65     14599_260325_143608.CMG   W9  2.8  78.0  81.6  139.5  []   []  []
66     14599_260325_150909.CMG  W10  0.7  88.3  90.1  119.8  []   []  []
67     14599_260325_152625.CMG  W11  1.2  87.4  89.6  118.8  []   []  []
68     14599_260325_154305.CMG  W12  3.8  81.2  84.4  115.6  []   []  []
69     14599_260325_170634.CMG  W13  1.1  89.8  92.0  128.8  []   []  []

[70 rows x 9 columns]

In [86]:
# df1 = df1.merge(
#     df2[['ID', 'U', 'LeqA', 'LeqC', 'Ppeak']],
#     left_on='ID_misura',
#     right_on='ID',
#     how='left',
#     indicator=True
# )

df2 = df2.merge(
    df1[['ID_misura']],
    left_on='ID',
    right_on='ID_misura',
    how = 'left',
    indicator=True
)
missing = df1.loc[df1['_merge'] == 'left_only', 'ID_misura'].unique().tolist()
# print(missing)

# df1 = df1.drop(columns=['ID', '_merge'])
# df1

,jobName,ID,U,LeqA,LeqC,Ppeak,Ti,GrOm,DPI,ID_misura,_merge
0,20260325_101842_103414.csv,F1,2.8,80.6,85.0,108.0,[],[],[],NaN,left_only
1,20260325_103430_105156.csv,F2,1.4,81.5,86.0,115.6,[],[],[],NaN,left_only
2,20260325_105210_111209.csv,F3,0.7,83.0,87.4,115.1,[],[],[],F3,both
3,20260325_111227_112948.csv,F4,1.8,82.9,87.0,107.5,[],[],[],NaN,left_only
4,20260325_113242_115130.csv,F5,0.6,77.9,81.5,102.3,[],[],[],NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...
65,14599_260325_143608.CMG,W9,2.8,78.0,81.6,139.5,[],[],[],NaN,left_only
66,14599_260325_150909.CMG,W10,0.7,88.3,90.1,119.8,[],[],[],NaN,left_only
67,14599_260325_152625.CMG,W11,1.2,87.4,89.6,118.8,[],[],[],NaN,left_only
68,14599_260325_154305.CMG,W12,3.8,81.2,84.4,115.6,[],[],[],NaN,left_only
69,14599_260325_170634.CMG,W13,1.1,89.8,92.0,128.8,[],[],[],NaN,left_only

In [96]:
list_grom = df1[df1.columns[0]].unique()
print('list grom = ',list_grom)

for i in list_grom:
    df = df1[df1[df1.columns[0]] == i]
    print(df)
    match_idx = df2.index[df2[df2.columns[1]].isin(df[df.columns[5]])].tolist()
    print(match_idx)

    df.loc[:, 'LAeq'] = df2.iloc[match_idx, 3].values
    print(df)

    
    
    
    # df.drop(df.columns[[0, 2, 3]], axis=1).to_excel('df_filtered.xlsx', index=False)

list grom =  [1 3]
   ID_GrOr      Descrizione_GrOr ID_reparto Descrizione_reparto  \
0        1      Addetto lavaggio         A1       Macello Polli
1        1  Adetto sollevamento         G19           Magazzino

                                 Descrizione_compito ID_misura   Ti  WBV  HAV
0  Qui va inserita la descrizione del gruppo omog...        D1  120   w1  NaN
1  Qui va inserita la descrizione del gruppo omog...        E4   60  NaN   h2
[19, 41]
   ID_GrOr      Descrizione_GrOr ID_reparto Descrizione_reparto  \
0        1      Addetto lavaggio         A1       Macello Polli
1        1  Adetto sollevamento         G19           Magazzino

                                 Descrizione_compito ID_misura   Ti  WBV  HAV  \
0  Qui va inserita la descrizione del gruppo omog...        D1  120   w1  NaN
1  Qui va inserita la descrizione del gruppo omog...        E4   60  NaN   h2

   LAeq
0  78.2
1  78.4
   ID_GrOr Descrizione_GrOr ID_reparto Descrizione_reparto  \
2        3  Linea di carico         G1           Magazzino

                                 Descrizione_compito ID_misura  Ti WBV  HAV
2  Qui va inserita la descrizione del gruppo omog...        F3   5  w3  NaN
[2]
   ID_GrOr Descrizione_GrOr ID_reparto Descrizione_reparto  \
2        3  Linea di carico         G1           Magazzino

                                 Descrizione_compito ID_misura  Ti WBV  HAV  \
2  Qui va inserita la descrizione del gruppo omog...        F3   5  w3  NaN

   LAeq
2  83.0

/var/folders/g9/z4b_4_ks01s65mk7dlq0rprh0000gn/T/ipykernel_24168/3054506970.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'LAeq'] = df2.iloc[match_idx, 3].values
/var/folders/g9/z4b_4_ks01s65mk7dlq0rprh0000gn/T/ipykernel_24168/3054506970.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'LAeq'] = df2.iloc[match_idx, 3].values

In [136]:
# Salvataggio di un file excel con più sheet

with pd.ExcelWriter('/Users/theo/Desktop/prova.xlsx', mode='a', engine='openpyxl') as writer:
    df2.to_excel(writer, sheet_name='Sheet12', index=False)

In [175]:
df = pd.read_excel('/Users/theo/Desktop/P.IVA/Aziende/Ermes/Lavori/SITITALIA spa.p/rev/rev/Rumore/scheda_gruppi_dpi.xlsx', sheet_name='Scheda_mansioni')
df[df['ID_GrOm'] == 3]['Descrizione_GrOm'].tolist()[0]

'Linea di carico'